[package]
edition = "2018"
name = "zap-demo"
version = "0.1.0"

[dependencies]
crossbeam-utils = "0.8.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lifo"
harness = false

[profile.test]
opt-level = 3